### ISSUE TITLE
Option API and Component API with Quasar v2

### ISSUE THREAD

**Issue by mpeirone** [quasarframework/app-extension-apollo#100]
Hi, is there a way to use Quasar V2 with apollo-vue Option API and Component API?

Thanks in advance

**Comment by smolinari** [comment]
@mpeirone - Unfortunately currently, only the composition API works with Quasar v2. This is an issue with the Vue-Apollo package.

Scott

**Comment by mpeirone** [comment]
@smolinari 
Are there other way to use GraphQL and option API with Quasar v2?

Matteo

**Comment by smolinari** [comment]
@mpeirone - Nope. 🤷 

Scott

**Comment by smolinari** [comment]
Closing as we are waiting for the upstream changes. Once they are getting close to done, we'll start new issues to note the additions. 

Scott
