### ISSUE TITLE
Usage with websockets

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/app-extension-apollo#104]
Since I won't have time to integrate this shortly, here are some random drafts about how you could use this package to support subscriptions via Websockets

https://github.com/IlCallo/app-extension-apollo/commit/65ba7fd3780ddf60bf666a6a925b98b143648a94

**Comment by ejez** [comment]
Hi @smolinari,

I might be of little help on this :disappointed:, as I'm  at the moment exploring a new stack/tools (web-components (lit, open-wc ...), urql for graphql, ...etc)

**Comment by smolinari** [comment]
This should be resolved with #141 

Scott
