### ISSUE TITLE
Infinite loading on SSR

### ISSUE THREAD

**Issue by keanugrieves** [quasarframework/app-extension-apollo#115]
I finally made the switch to Quasar 2, and in SSR mode, I'm stuck in an infinite loop whenever I add similar queries to components that are loading simultaneously, e.g.

**MainLayout.vue**

```
query MainLayoutCurrentUser {
  currentUser {
    id
    role
  }
}
```

**MainHeader.vue**

```
query MainHeaderCurrentUser {
  currentUser {
    id
  }
}
```

It's blazing fast when I load just one of those queries, or if I disable SSR entirely, but otherwise, it's stuck forever.

Other fixes I've tried:

- Disabling query deduplication
- Removing router guards (which also call a currentUser query in the apollo.js boot file)
- Upgrading @vue/apollo-composable to v4.0.0-alpha.16

I'm really at a loss here as to how to fix it. The only similar issue was a Vue 2 problem that was supposedly fixed in https://github.com/vuejs/vue-apollo/pull/1241

Any ideas?

**Comment by smolinari** [comment]
@keanugrieves - sorry for the late reply. I'm totally new to SSR. Could you possible make a minimum reproduction of the issue? I'll see if I can get other eyes onto it too, once you do. 

Scott

**Comment by smolinari** [comment]
A side note/ question, but if the app is for an admin dashboard, SSR isn't really necessary, is it?

Scott

**Comment by keanugrieves** [comment]
I'm also working on three child sites all feeding off of that admin dashboard, which incorporate auth tokens and need SSR (for Facebook sharing meta tags), so I was hoping to get comfortable with it before I do those.

This project is unimaginably large for someone with my experience and skill set, so if you have a minute, are feeling generous and have any large-scale suggestions for reimagining this whole project, I'd love to chat on Discord.

Side question: will m8a be SSR-capable?

**Comment by smolinari** [comment]
@keanugrieves - Sorry this got dropped. Did you get further? I'm closing for now, but if you need anything you can reopen or create a new issue. 

Scott
