### ISSUE TITLE
Quasar 2 + Apollo: Error: Apollo client with id default not found. Use provideApolloClient() if you are outside of a component setup

### ISSUE THREAD

**Issue by lee3star** [quasarframework/app-extension-apollo#116]
followed the steps in https://github.com/quasarframework/app-extension-apollo/tree/v2 to install Apollo extension to Quasar 2.4.9:

```
  "devDependencies": {
    "@babel/eslint-parser": "^7.13.14",
    "@quasar/app": "^3.0.0",
    "@quasar/quasar-app-extension-apollo": "^2.0.0-beta.3",
    "eslint": "^7.14.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-vue": "^7.0.0",
    "eslint-webpack-plugin": "^2.4.0"
  },
```

found two files generated which are related to apollo:

- src/boot/apollo.js
- src/apollo/index.js, where I modified the process.env.GRAPHQL_URI to be my GraphQL server endpoint

I also manually created apollo.provider.js under the root directory with :

```
// apollo.config.js
module.exports = {
  client: {
    service: {
      name: "my-app",
      // URL to the GraphQL API
      url: "http://localhost:4000/graphql",
    },
    // Files processed by the extension
    includes: ["src/**/*.vue", "src/**/*.js"],
  },
};
```

in my Vue file, I have the following code:

```
<script>
import { useQuery } from "@vue/apollo-composable";
import gql from "graphql-tag";
export default {
  setup() {
    const { result } = useQuery(gql`
      query GetAllBooks {
        getAllBooks {
          id
          name
        }
      }
    `);
  },
...
```

However, running this code led to the following error:

```
index.esm.js?0df5:48 Uncaught (in promise) Error: Apollo client with id default not found. Use provideApolloClient() if you are outside of a component setup.
    at resolveClient (index.esm.js?0df5:48:1)
    at start (index.esm.js?0df5:277:1)
    at immediate (index.esm.js?0df5:493:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js?9e79:6737:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?9e79:6746:1)
    at job (runtime-core.esm-bundler.js?9e79:7154:1)
    at doWatch (runtime-core.esm-bundler.js?9e79:7199:1)
    at watch (runtime-core.esm-bundler.js?9e79:7040:1)
    at useQueryImpl (index.esm.js?0df5:491:1)
    at useQuery (index.esm.js?0df5:228:1)
```

Any idea which part's wrong?

I found this post [I am using vue 3 with apollo/client but getting an error](https://stackoverflow.com/questions/65850813/i-am-using-vue-3-with-apollo-client-but-getting-an-error), seems Ricky Vadala's also using Quasar and following the same steps. However, the following doesn't work for me:

```
  import { apolloClients } from 'src/extensions/apollo/boot'
```
as 'src/extensions/apollo/boot' does not exist.

Also, I cannot find your-app\node_modules@quasar\quasar-app-extension-apollo\README.md. Maybe Ricky Vadala was using an older version?

Please kindly shed some light on this. Surprisingly I cannot find an example of Quasar 2 + Apollo from the Internet.

**Comment by smolinari** [comment]
Can you make a minimum reproduction? Hard to tell what might be wrong with the info given. 

Scott

**Comment by lee3star** [comment]
thanks Scott, below are the steps: 

1) create a quasar project

```
➜  js quasar create testApollo

  ___
 / _ \ _   _  __ _ ___  __ _ _ __
| | | | | | |/ _` / __|/ _` | '__|
| |_| | |_| | (_| \__ \ (_| | |
 \__\_\\__,_|\__,_|___/\__,_|_|



? Project name (internal usage for dev) testapollo
? Project product name (must start with letter if building mobile apps) Quasar A
pp
? Project description A Quasar Framework app
? Author
? Pick your CSS preprocessor: SCSS
? Check the features needed for your project: ESLint (recommended)
? Pick an ESLint preset: Prettier
? Continue to install project dependencies after the project has been created? (
recommended) NPM

  Quasar CLI · Generated "testApollo".


 [*] Installing project dependencies ...

npm WARN deprecated @types/webpack-dev-middleware@5.3.0: This is a stub types definition. webpack-dev-middleware provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/compression-webpack-plugin@9.1.1: This is a stub types definition. compression-webpack-plugin provides its own type definitions, so you do not need this installed.

added 951 packages, and audited 952 packages in 53s

120 packages are looking for funding
  run `npm fund` for details

4 low severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.


 [*] Running eslint --fix to comply with chosen preset rules...



> testapollo@0.0.1 lint
> eslint --ext .js,.vue ./ "--fix"


 [*] Quasar Project initialization finished!

To get started:

  cd testApollo
  quasar dev

Documentation can be found at: https://quasar.dev

Quasar is relying on donations to evolve. We'd be very grateful if you can
read our manifest on "Why donations are important": https://quasar.dev/why-donate
Donation campaign: https://donate.quasar.dev
Any amount is very welcomed.
If invoices are required, please first contact razvan@quasar.dev

Please give us a star on Github if you appreciate our work:
https://github.com/quasarframework/quasar

Enjoy! - Quasar Team

```

2) install apollo plugin by following https://github.com/quasarframework/app-extension-apollo/tree/v2

```
➜  js cd testApollo
➜  testApollo quasar ext add @quasar/apollo@next
 App • Installing "@quasar/apollo" Quasar App Extension

 App • Retrieving "@quasar/quasar-app-extension-apollo@next"...
 App • [sync] Running "npm install --save-dev @quasar/quasar-app-extension-apollo@next"


added 22 packages, and audited 974 packages in 11s

121 packages are looking for funding
  run `npm fund` for details

4 low severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
? Does your app have typescript support? No

 App • Updating /quasar.extensions.json for "@quasar/apollo" extension ...
 App • Running App Extension install script...
 App • Quasar App Extension "@quasar/apollo" successfully installed.
```

3) modify apollo.config.js under root directory to use my graphql endpoint

```
'use strict'
/* eslint-env node */
// See https://www.apollographql.com/docs/devtools/apollo-config/
module.exports = {
  client: {
    service: {
      name: 'my-service',
      url: 'http://localhost:4000/graphql',
    },
    // Files processed by the extension
    includes: ['src/**/*.vue', 'src/**/*.js', 'src/**/*.ts'],
  },
}
```

4) edit src/pages/Error404.vue(just a test using out-of-the-box assets) to be the following to test apollo code

```
<template>
  <h1>TEST</h1>
</template>

<script>
import { useQuery } from "@vue/apollo-composable";
import gql from "graphql-tag";

export default {
  setup() {
    const { result } = useQuery(gql`
      query GetAllBooks {
        getAllBooks {
          id
          name
        }
      }
    `);
  },
};
</script>

5) start quasar, running into dependency isue

```
quasar dev                        

 Dev mode.......... spa
 Pkg quasar........ v2.4.10
 Pkg @quasar/app... v3.2.6
 Pkg webpack....... v5
 Debugging......... enabled

 Configured browser support (>= 89.34% of global marketshare):
 · Chrome for Android >= 96
 · Firefox for Android >= 95
 · Android >= 96
 · Chrome >= 88
 · Edge >= 94
 · Firefox >= 87
 · iOS >= 12.0-12.1
 · Opera >= 78
 · Safari >= 13

 App • Running "@quasar/apollo" Quasar App Extension...

 App • ⚠️  ️️Setting port to closest one available: 8081

 App • Extension(@quasar/apollo): Extending quasar.conf...
 App • Chaining "UI" Webpack config
 App •  WAIT  • Compiling of "UI" in progress...
 App •  DONE  • "UI" compiled with errors • 7512ms



 App •  ERROR  •  UI  in ./src/pages/Error404.vue?vue&type=script&lang=js

Module not found: Can't resolve imported dependency "@vue/apollo-composable"
Did you forget to install it? You can run: npm install --save @vue/apollo-composable


 App •  COMPILATION FAILED  • Please check the log above for details.
```

6) fix the dependency issue

```
➜  testApollo npm install --save @vue/apollo-composable

added 2 packages, removed 2 packages, and audited 974 packages in 8s

121 packages are looking for funding
  run `npm fund` for details

4 low severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

7) start again 

```
➜  testApollo quasar dev                               

 Dev mode.......... spa
 Pkg quasar........ v2.4.10
 Pkg @quasar/app... v3.2.6
 Pkg webpack....... v5
 Debugging......... enabled

 Configured browser support (>= 89.34% of global marketshare):
 · Chrome for Android >= 96
 · Firefox for Android >= 95
 · Android >= 96
 · Chrome >= 88
 · Edge >= 94
 · Firefox >= 87
 · iOS >= 12.0-12.1
 · Opera >= 78
 · Safari >= 13

 App • Running "@quasar/apollo" Quasar App Extension...

 App • ⚠️  ️️Setting port to closest one available: 8081

 App • Extension(@quasar/apollo): Extending quasar.conf...
 App • Chaining "UI" Webpack config
 App •  WAIT  • Compiling of "UI" in progress...
 App •  DONE  • "UI" compiled with success • 6697ms



 App •  READY  • Compiled: "UI"

 » App dir........... /Users/sean.li/Dev/js/testApollo
 » App URL........... http://localhost:8081
                      http://192.168.1.77:8081
 » Dev mode.......... spa
 » Pkg quasar........ v2.4.10
 » Pkg @quasar/app... v3.2.6
 » Transpiled JS..... yes (Babel)

 App • Opening default browser at http://localhost:8081
```

8) started with a browser window popped up: http://localhost:8081/#/

9) browse to http://localhost:8081/#/404 with Chrome dev tools open, got the following: 

```
vue-router.esm-bundler.js?f6c4:3295 Error: Apollo client with id default not found. Use provideApolloClient() if you are outside of a component setup.
    at resolveClient (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:60:13)
    at start (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:289:20)
    at immediate (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:505:7)
    at callWithErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6829:22)
    at callWithAsyncErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6838:21)
    at job (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7243:17)
    at doWatch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7288:13)
    at watch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7129:12)
    at useQueryImpl (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:503:50)
    at useQuery (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:240:10)
triggerError @ vue-router.esm-bundler.js?f6c4:3295
index.esm.js?0df5:48 Uncaught (in promise) Error: Apollo client with id default not found. Use provideApolloClient() if you are outside of a component setup.
    at resolveClient (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:60:13)
    at start (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:289:20)
    at immediate (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:505:7)
    at callWithErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6829:22)
    at callWithAsyncErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6838:21)
    at job (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7243:17)
    at doWatch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7288:13)
    at watch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7129:12)
    at useQueryImpl (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:503:50)
    at useQuery (webpack-internal:///./node_modules/@vue/apollo-composable/dist/index.esm.js:240:10)
```

Hope the steps are clear. Please let me know whether I'm missing anything.

**Comment by smolinari** [comment]
Oof. Thanks. But, a minimum reproduction is simply a repository with minimum code to be able to reproduce the error. :)

I'll have a read through your reproduction and see if I can spot an issue though.

Scott

**Comment by smolinari** [comment]
Ok. I hopefully did the same mistake you did and didn't follow the instructions in the README completely. 

Did you also forget to register the boot file in `quasar.conf.js`?

Once I did that, the missing defaultClient error went away. 

Scott

**Comment by lee3star** [comment]
that did the magic! thanks Scott. I will need to read the README more carefully...

**Comment by smolinari** [comment]
@lee3star - When I update the package to GA, (hopefully very soon, as I'm waiting for `@vue/apollo` v4 to be moved out of alpha), I'll either see if I can't auto-register the boot file via the install script or improve the docs to make the step much clearer.

Scott

**Comment by lee3star** [comment]
thanks Scott, auto-register would make it much easier.

**Comment by smolinari** [comment]
@ricar2ce - Please open a new issue and if need be, refer to this one. Thanks.  

Scott
