### ISSUE TITLE
quasar build -m pwa not using GRAPHQL_URI

### ISSUE THREAD

**Issue by estenssoros** [quasarframework/app-extension-apollo#118]
I am attempting to build a pwa with quasar using `GRAPHQL_URI=<my-ep>  quasar build -m pwa`. However, when running `quasar serve` from the pwa directory, the graphql requests keep defaulting to the local  URI  `process.env.GRAPHQL_URI || 'http://127.0.0.1:1323/graph'`

I am using the v2 branch of app-extension-apollo and am a little new to Vue so I might just be doing something silly here but I saw in the docs this was the way to build the app with environment variables for the graphgql endpoint

**Comment by smolinari** [comment]
@estenssoros - Can you link me to where this is noted in the docs please? Because I'm thinking building and running an app are are two different steps. So, your env variable won't be available when running, only when building. 

Scott

**Comment by estenssoros** [comment]
sure! it's in the readme for the project https://git hub.com/quasarframework/app-extension-apollo/tree/v2 under `Apollo Client options`. 
```
GRAPHQL_URI=https://prod.example.com/graphql quasar build
GRAPHQL_URI=https://dev.example.com/graphql quasar dev
```

**Comment by estenssoros** [comment]
ok i figured it out. 
this needs to be added to `quasar.conf.js`
```
```
