### ISSUE TITLE
Error: Apollo client with id default not found. Use provideApolloClient() if you are outside of a component setup, in the q-dialog (modal)

### ISSUE THREAD

**Issue by ricar2ce** [quasarframework/app-extension-apollo#128]
Hello,
i am getting "`Error: Apollo client with id default not found. Use provideApolloClient() if you are outside of a component setup`" when i make use of extension inside q-dialog (modal) component.
I have made sure that my apollo boot file is register in quasar.conf.js, and any other needed config and the extension works perfectly outside of q-dialog.

I temporarily had to recreate a whole client inside the component, 
```js
import { ApolloClient , createHttpLink, InMemoryCache  } from '@apollo/client/core'
import { provideApolloClient} from '@vue/apollo-composable'

const apolloClient = new ApolloClient({
  link: createHttpLink({
    uri:'http://localhost:5000/graphql',
  }),
  cache: new InMemoryCache(),
})

provideApolloClient(apolloClient);

export default {
  name: ...
```
but it doesn't seem like an optimal solution.

any other ideas to fix this?
thanks in advance

**Comment by smolinari** [comment]
I haven't tried it myself, but did you try putting `provideApolloClient` inside the boot file after the client is initialized?

Scott

**Comment by ricar2ce** [comment]
> I haven't tried it myself, but did you try putting `provideApolloClient` inside the boot file after the client is initialized?
> 
> Scott

this is my apollo boot file:
```js

export default boot(
 ({ app }) => {
    // Default client.
    const options = /* await */ getClientOptions(/* {app, router ...} */)
    const apolloClient = new ApolloClient(options)
    
    const apolloClients = {
      default: apolloClient,
    }
    app.provide(ApolloClients, apolloClients)
  }
)
```

**Comment by smolinari** [comment]
Yes, try adding `provideApolloClient` inside the `boot` method. 

Scott
