### ISSUE TITLE
Minor request

### ISSUE THREAD

**Issue by newalphamedia** [quasarframework/app-extension-apollo#129]
Hey, just to make the documentation a little more clear for anyone else who is having the **Apollo client with id default not found** error, perhaps we could add after this line:

_The extension will add a configuration file into src/apollo and a boot file. You'll need to manually register the latter into quasar.conf.js > boot._

Something like this:

**If you are running into any issues with "id default not found", make sure you have edited your quasar.config.js to add "apollo.ts" (or .js) to the "boot" section.**
For example: boot: ['apollo.ts']

**Comment by smolinari** [comment]
Feel free to add the comment. PRs are welcome. 

Scott
