### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by dmitry** [quasarframework/app-extension-apollo#13]
Please add SSR support to the apollo as well, especially the state restoration.
Probably it requries to control possibility to add `inject: false` to the `createRenderer` method in `dev-server` and production server.

**Comment by dmitry** [comment]
When using apollo as a boot state restoration can be made with:

```javascript
    {{{ renderState({ contextKey: 'apolloState', windowKey: '__APOLLO_STATE__' }) }}}
    <div id="q-app"></div>
```

It must be before `q-app` div, as `q-app` is a placeholder which is going to be replaced while the app execution.

Then in boot/apollo.js you need to do:

```javascript
    if (!process.env.SERVER && typeof window !== "undefined") {
      const state = window.__APOLLO_STATE__;
      if (state) {
        cache.restore(state.defaultClient);
      }
    }
```

And somewhere in the bottom of the apollo boot file you have to push `apolloState` back to the `ssrContext` once everything is rendered:

```javascript
    router.onReady(() => {
      if (process.env.SERVER) {
        ssrContext.rendered = () => {
          ssrContext.apolloState = ApolloSSR.getStates(apolloProvider)
        }
      }
    })
```

**Comment by smolinari** [comment]
Hey. We've got @ejez doing some work on the AE and he's making it SSR ready. Looking for testers. 😃 

Scott
