### ISSUE TITLE
First call affter Page reload anytime gives me an undefined 

### ISSUE THREAD

**Issue by Subsonic00** [quasarframework/app-extension-apollo#132]
Hello,
after I solved the Problem to run GraphQL with Quasar, now the next problem jumping in my face. Anytime if I reload the page the first result of the graphql request is undefined and with 2nd request i get the result. This is weird and I dont find any solution for this. I hope u can help me with this.

How I send the request(initToken isn't empty)
![image](https://user-images.githubusercontent.com/77988964/190253938-57ed38c4-7e52-4407-a646-96d1310f34e8.png)

apollo.js
![image](https://user-images.githubusercontent.com/77988964/190253387-eaf5edf4-4f54-4b27-adcf-8699ac876072.png)

I hope u can help me with this weird problem 

Greetings
Subsonic

**Comment by smolinari** [comment]
I'm assuming this is to see if a user is logged in or not via a token. This logic shouldn't be in a component. It should be in your boot system, where you set up your http link. See this for reference: 

https://www.apollographql.com/docs/react/networking/authentication/

**Comment by juferdinand** [comment]
Hello I'm one of the two developers which found the problem. This is not the Problem which we have, I know that Headers or something else should be set in the boot file. But if I send any GraphQL  Request via useQuery I get first time undefined. If u read result.value, but the result is there if I print the completly result into the console. 
Value is undefined, but _rawvalue is as example is not undefined and loading is anytime true in first call to Api. U know this Issue or should I share some more information?

**Comment by smolinari** [comment]
@juferdinand - I don't know about any such issue. And especially because I personally use the composition API. You might try using a hook to call the first time to prime the data. Also, `@vue/apollo-composable` was meant to be used with the composition API and using `setup()`. You seem to be using the options API. Are you using Vue 3 or Vue 2 (Quasar v2 or v1)? And if Vue 2/ Quasar v1), you should be using `@vue/apollo-options` as the docs say. https://v4.apollo.vuejs.org/guide-option/setup.html

Scott

**Comment by juferdinand** [comment]
We using Quasar V2 so Vue3, so it looks like we did something false. Have u maybe an example how we should do it? We found not much about this, we was happy that it was running 😂

**Comment by smolinari** [comment]
The vue-apollo docs show how it should be done. I gave you a link above. 

Scott

**Comment by juferdinand** [comment]
there is apollo-options in use, u mean we have to use apollo-composable or should we switch completly to options?

**Comment by smolinari** [comment]
You should use @vue/apollo-options. @vue/apollo-composable is for the composition API. Or, change to the composition API. 

Scott

**Comment by smolinari** [comment]
Closing. If you feel there is still an issue, please re-open. 

Scott
