### ISSUE TITLE
graphql-tag dependency issues

### ISSUE THREAD

**Issue by mandofever78** [quasarframework/app-extension-apollo#134]
I have just migrated to Quasar v2 (Vue 3) with Vite integration and in the process of upgrading this extension I had to adjust my approach to importing my queries/mutations from dedicated files as such:

```
import gql from 'graphql-tag'

const FetchCurrentUser = gql`
  query FetchCurrentUser {
    currentUser @client {
      id
      name
      phone
      email
      title
      role {
        id
        name
      }
    }
  }
`;

export { FetchCurrentUser }
```

While this approach is currently functional, the Apollo v3 migration docs recommend that all references to 'graphql-tag' be replaced with the new '@apollo/client' package since it has included graphql-tag as as dependency. The problem is that using `import gql from '@apollo/client'` results In bundling errors due to Vite's rollup attempting and failing to reference non-existent 'react' packages. I also unsuccessfully attempted to exclude the react from the rollup using:

```
rollupOptions: {
  external: ['react'],
},
```

Any thoughts on what the correct approach should be?

**Comment by smolinari** [comment]
@mandofever78 - Try importing `gql` from `@apollo/client/core` and as a named export. So, 

```ts
import { gql } from '@apollo/client/core'
```

Scott

**Comment by mandofever78** [comment]
Yep, that works for me as well. Thanks for the prompt response!
