### ISSUE TITLE
Apollo Client not compatible with Quasar II ?

### ISSUE THREAD

**Issue by fabianmarcus** [quasarframework/app-extension-apollo#135]
When I try to use your extension with Quasar II the following is thrown during initialization:

```
Extension(@quasar/apollo): is not compatible with quasar v2.10.1. Required version: ^1.5.1
```

Is there any way to use your Apollo Client with the latest Quasar version?

**Comment by smolinari** [comment]
@fabianmarcus - Switch to the v2 branch for the Qv2 as the readme says. 

![image](https://user-images.githubusercontent.com/3314957/201600164-45b2d008-2808-45e4-bc70-6a454b38025d.png)

https://github.com/quasarframework/app-extension-apollo/tree/v2

Scott
