### ISSUE TITLE
Error in Quasar ssr with @vue/apollo-composable

### ISSUE THREAD

**Issue by AhmadKhaj** [quasarframework/app-extension-apollo#137]
Hello Scott
I  add apollo to quasar project with app-extension-apollo by documentation.
first get an error that @vue/apollo-composable not found and i install it manually.
now with command quasar dev -m ssr get below error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module D:\quasar-apollo-ssr\quasar-project\node_modules\@apollo\client\core\index.js from D:\quasar-apollo-ssr\quasar-project\node_modules\@vue\apollo-composable\dist\index.js not supported.
Instead change the require of D:\quasar-apollo-ssr\quasar-project\node_modules\@apollo\client\core\index.js in D:\quasar-apollo-ssr\quasar-project\node_modules\@vue\apollo-composable\dist\index.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by smolinari** [comment]
Are you following these instructions?

https://github.com/quasarframework/app-extension-apollo/tree/v2

Scott

**Comment by AhmadKhaj** [comment]
> Are you following these instructions?
> 
> https://github.com/quasarframework/app-extension-apollo/tree/v2
> 
> Scott

Yes and this works in SPA but in SSR has this error

**Comment by smolinari** [comment]
Can you show me your repository? Or more specifically, how you've created your bootfile?

Scott

**Comment by ipalestine** [comment]
github repository:
    https://github.com/ipalestine/q-apollo-ssr
full error message: 
 [vite] Error when evaluating SSR module /src/boot/apollo.js:
Error [ERR_REQUIRE_ESM]: require() of ES Module D:\q-apollo-ssr\quasar-project\node_modules\@apollo\client\core\index.js from D:\q-apollo-ssr\quasar-project\node_modules\@vue\apollo-composable\dist\index.js not supported.
Instead change the require of D:\q-apollo-ssr\quasar-project\node_modules\@apollo\client\core\index.js in D:\q-apollo-ssr\quasar-project\node_modules\@vue\apollo-composable\dist\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (D:\q-apollo-ssr\quasar-project\node_modules\@vue\apollo-composable\dist\index.js:259:30)
    at async Promise.all (index 0)
    at async nodeImport (D:\q-apollo-ssr\quasar-project\node_modules\vite\dist\node\chunks\dep-689425f3.js:50387:21)
    at async eval (/src/boot/apollo.js:5:31)
    at async instantiateModule (D:\q-apollo-ssr\quasar-project\node_modules\vite\dist\node\chunks\dep-689425f3.js:50317:9)
D:\q-apollo-ssr\quasar-project\node_modules\@vue\apollo-composable\dist\index.js:259
var import_core = __toModule(require("@apollo/client/core/index.js"));
                             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module D:\q-apollo-ssr\quasar-project\node_modules\@apollo\client\core\index.js from D:\q-apollo-ssr\quasar-project\node_modules\@vue\apollo-composable\dist\index.js not supported.
Instead change the require of D:\q-apollo-ssr\quasar-project\node_modules\@apollo\client\core\index.js in D:\q-apollo-ssr\quasar-project\node_modules\@vue\apollo-composable\dist\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (D:\q-apollo-ssr\quasar-project\node_modules\@vue\apollo-composable\dist\index.js:259:30)
    at async Promise.all (index 0)
    at async nodeImport (D:\q-apollo-ssr\quasar-project\node_modules\vite\dist\node\chunks\dep-689425f3.js:50387:21)
    at async eval (/src/boot/apollo.js:5:31)
    at async instantiateModule (D:\q-apollo-ssr\quasar-project\node_modules\vite\dist\node\chunks\dep-689425f3.js:50317:9) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by smolinari** [comment]
This is unfortunately an error with vue/apollo-composable. We'll have to wait for the upstream to fix. 

Scott

**Comment by ipalestine** [comment]
is there an alternative  way for this?
