### ISSUE TITLE
@vue/apollo-composable

### ISSUE THREAD

**Issue by ipalestine** [quasarframework/app-extension-apollo#139]
Hello,

I run:

`quasar ext add @quasar/apollo@next`

And add 'apollo' to quasar.config.js->boot and run:

`quasar dev`

then this error was printed :

`

 [vite] Internal server error: Failed to resolve import "@vue/apollo-composable" from "src\boot\apollo.js". Does the file exist?
  Plugin: vite:import-analysis
  File: E:/STORE/client/src/boot/apollo.js
  1  |  import { ApolloClient /*, createHttpLink */ } from '@apollo/client/core'
  2  |  import { ApolloClients } from '@vue/apollo-composable'
     |                                 ^
  3  |  import { boot } from 'quasar/wrappers'
  4  |  import { getClientOptions } from 'src/apollo'
      at formatError (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39080:46)
      at TransformContext.error (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39076:19)
      at normalizeUrl (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:58360:26)
      at async TransformContext.transform (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:58509:57)
      at async Object.transform (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39317:30)
      at async doTransform (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:50043:29)`

Then i install @vue/apollo-composable manually that this work in SPA mode but in SSR mode printed blow error and stops app:

۱۴:۵۳:۱۷ [vite] Error when evaluating SSR module /src/boot/apollo.js:
Error [ERR_REQUIRE_ESM]: require() of ES Module E:\STORE\client\node_modules\@apollo\client\core\index.js from E:\STORE\client\node_modules\@vue\apollo-composable\dist\index.js not supported.
Instead change the require of E:\STORE\client\node_modules\@apollo\client\core\index.js in E:\STORE\client\node_modules\@vue\apollo-composable\dist\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (E:\STORE\client\node_modules\@vue\apollo-composable\dist\index.js:250:30)
    at async Promise.all (index 0)
    at async nodeImport (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:50387:21)
    at async eval (/src/boot/apollo.js:5:31)
    at async instantiateModule (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:50317:9)
E:\STORE\client\node_modules\@vue\apollo-composable\dist\index.js:250
var import_core = __toModule(require("@apollo/client/core/index.js"));
                             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module E:\STORE\client\node_modules\@apollo\client\core\index.js from E:\STORE\client\node_modules\@vue\apollo-composable\dist\index.js not supported.
Instead change the require of E:\STORE\client\node_modules\@apollo\client\core\index.js in E:\STORE\client\node_modules\@vue\apollo-composable\dist\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (E:\STORE\client\node_modules\@vue\apollo-composable\dist\index.js:250:30)
    at async Promise.all (index 0)
    at async nodeImport (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:50387:21)
    at async eval (/src/boot/apollo.js:5:31)
    at async instantiateModule (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:50317:9) {
  code: 'ERR_REQUIRE_ESM'
}

`

Quasar information:

Operating System - Windows_NT(10.0.19045) - win32/x64
NodeJs - 16.15.1

Global packages
  NPM - 8.11.0
  yarn - Not installed
  @quasar/cli - 2.2.1
  @quasar/icongenie - Not installed
  cordova - 11.1.0

Important local packages
  quasar - 2.12.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.4.3 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.4 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.2
  pinia - Not installed
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.42.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-apollo - 2.0.0-beta.5 -- A Quasar app extension to add GraphQL support using Apollo Client.

Networking
  Host - RASAP
  Ethernet - 192.168.1.100`
`

**Comment by ipalestine** [comment]
> Hello,
> 
> I run:
> 
> `quasar ext add @quasar/apollo@next`
> 
> And add 'apollo' to quasar.config.js->boot and run:
> 
> `quasar dev`
> 
> then this error was printed :
> 
> `
> 
> [vite] Internal server error: Failed to resolve import "@vue/apollo-composable" from "src\boot\apollo.js". Does the file exist? Plugin: vite:import-analysis File: E:/STORE/client/src/boot/apollo.js 1 | import { ApolloClient /*, createHttpLink */ } from '@apollo/client/core' 2 | import { ApolloClients } from '@vue/apollo-composable' | ^ 3 | import { boot } from 'quasar/wrappers' 4 | import { getClientOptions } from 'src/apollo' at formatError (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39080:46) at TransformContext.error (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39076:19) at normalizeUrl (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:58360:26) at async TransformContext.transform (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:58509:57) at async Object.transform (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39317:30) at async doTransform (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:50043:29)`
> 
> Then i install @vue/apollo-composable manually that this work in SPA mode but in SSR mode printed blow error and stops app:
> 
> ۱۴:۵۳:۱۷ [vite] Error when evaluating SSR module /src/boot/apollo.js: Error [ERR_REQUIRE_ESM]: require() of ES Module E:\STORE\client\node_modules@apollo\client\core\index.js from E:\STORE\client\node_modules@vue\apollo-composable\dist\index.js not supported. Instead change the require of E:\STORE\client\node_modules@apollo\client\core\index.js in E:\STORE\client\node_modules@vue\apollo-composable\dist\index.js to a dynamic import() which is available in all CommonJS modules. at Object. (E:\STORE\client\node_modules@vue\apollo-composable\dist\index.js:250:30) at async Promise.all (index 0) at async nodeImport (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:50387:21) at async eval (/src/boot/apollo.js:5:31) at async instantiateModule (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:50317:9) E:\STORE\client\node_modules@vue\apollo-composable\dist\index.js:250 var import_core = __toModule(require("@apollo/client/core/index.js")); ^
> 
> Error [ERR_REQUIRE_ESM]: require() of ES Module E:\STORE\client\node_modules@apollo\client\core\index.js from E:\STORE\client\node_modules@vue\apollo-composable\dist\index.js not supported. Instead change the require of E:\STORE\client\node_modules@apollo\client\core\index.js in E:\STORE\client\node_modules@vue\apollo-composable\dist\index.js to a dynamic import() which is available in all CommonJS modules. at Object. (E:\STORE\client\node_modules@vue\apollo-composable\dist\index.js:250:30) at async Promise.all (index 0) at async nodeImport (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:50387:21) at async eval (/src/boot/apollo.js:5:31) at async instantiateModule (E:\STORE\client\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:50317:9) { code: 'ERR_REQUIRE_ESM' }
> 
> `
> 
> Quasar information:
> 
> Operating System - Windows_NT(10.0.19045) - win32/x64 NodeJs - 16.15.1
> 
> Global packages NPM - 8.11.0 yarn - Not installed @quasar/cli - 2.2.1 @quasar/icongenie - Not installed cordova - 11.1.0
> 
> Important local packages quasar - 2.12.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time @quasar/app-vite - 1.4.3 -- Quasar Framework App CLI with Vite @quasar/extras - 1.16.4 -- Quasar Framework fonts, icons and animations eslint-plugin-quasar - Not installed vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI. vue-router - 4.2.2 pinia - Not installed vuex - Not installed vite - 2.9.16 -- Native-ESM powered web dev build tool eslint - 8.42.0 -- An AST-based pattern checker for JavaScript. electron - Not installed electron-packager - Not installed electron-builder - Not installed register-service-worker - 1.7.2 -- Script for registering service worker, with hooks @capacitor/core - Not installed @capacitor/cli - Not installed @capacitor/android - Not installed @capacitor/ios - Not installed
> 
> Quasar App Extensions @quasar/quasar-app-extension-apollo - 2.0.0-beta.5 -- A Quasar app extension to add GraphQL support using Apollo Client.
> 
> Networking Host - RASAP Ethernet - 192.168.1.100` `

Update:
I uninstall @vue/apollo-composable and run quasar dev and this time it works in the both SPA and SSR but apolloState not set in the rendered page in the server

**Comment by smolinari** [comment]
Not sure what to say here. I'm going to close it for lack of interest. If there is still an issue, please feel free to reopen. 

Scott
