### ISSUE TITLE
[Quasar] boot error: SyntaxError: missing name after . operator

### ISSUE THREAD

**Issue by ipalestine** [quasarframework/app-extension-apollo#154]
After add apollo to project with ext command and add it to boot section of quasar config this error ocurred: 

[Quasar] boot error: SyntaxError: missing name after . operator

**Comment by darqus** [comment]
confirming this behavior
the project becomes inoperable

// @vue/apollo-composable
// SyntaxError: missing name after . operator
import { useQuery, useResult, } from '@vue/apollo-composable'

**Comment by yusufkandemir** [comment]
This is most likely the same problem as https://github.com/quasarframework/quasar/issues/16060
These are the messages for the same error in different browsers:
> SyntaxError: Unexpected string (Chrome)
> SyntaxError: missing name after . operator (Firefox)
> SyntaxError: Unexpected token '"'. Expected a property name after '.'. (Safari)

`graphql` package accesses `process.env` like `globalThis.process.env.NODE_ENV` which gets replaced to `globalThis."development"`/`globalThis."production"` during dev/build process. So, either the `graphql` package needs to address this, or we can work around it by converting `globalThis.process.env.NODE_ENV` as a whole. I will create a PR to apply this workaround.
