### ISSUE TITLE
Production Build

### ISSUE THREAD

**Issue by rikoz** [quasarframework/app-extension-apollo#18]
Please when will this extention be ready for use??

STILL IN DEVELOPMENT??

Specify what's left so we can complete it

**Comment by rstoenescu** [comment]
Hi,

Seeing all this rude yelling (the caps) makes me answer this thread with trash talk, but I'll try not to do that. The yelling shows a clear misconception about how opensource works. I'd like to see some appreciation for the MANY free stuff that we are releasing each day and the amount of almostly unpaid work that we are doing so all the community can make money off of it.

To put things in perspective:

1. Using Apollo with Quasar is NOT hindered by the creation of this App Extension. It's not like if this doesn't gets finished fast, Apollo is not available in the Quasar ecosystem. Quasar is backend agnostic, so you can hook ANY such service into it.
2. This AE will just offer a nice way (might be opinionated) out of the box for injecting necessary Apollo stuff into a Quasar app. Nothing more. There's already many github repos that show how it can be achieved. But there's nothing special regarding doing it with Quasar.
3. This AE has been wrongfully spawned without a clear roadmap (and so milestones) for it and without a clear responsible for it -- initially when it was proposed to me, I was under the impression that this is not the case.
4. This AE requires a considerable effort on the Team, and we have no one available resources to push it forward (**for the time being**). Both in terms of human resources and financial support (although the latter might alleviate the first one).

We are looking towards assigning this AE to someone to take care of it.
