### ISSUE TITLE
Ask user, if other GraphQL backends should be installed (i.e. Prisma or Yoga)

### ISSUE THREAD

**Issue by smolinari** [quasarframework/app-extension-apollo#30]
As a user, I'd like to have the option to have a more advanced GraphQL server installed via the AE. This is a nice to have and isn't required for v1.0. 

Examples of more advanced servers are Prisma and Yoga.

Scott

**Comment by ejez** [comment]
I think it is better to keep the ext focused on the task of implementing graphql in quasar (concept of micro services, doing one thing and doing it well), the objective of the ext is to facilitate integrating graphql in quasar, not teaching how to use graphql, for that people can find plenty of stuff online, we can also provide links in the README file

@rstoenescu

**Comment by smolinari** [comment]
Yeah I agree. We could have another app extension doing this.

Scott
