### ISSUE TITLE
Websocket Support for Subscriptions

### ISSUE THREAD

**Issue by AndrewAlegre** [quasarframework/app-extension-apollo#37]
Hi, just curious if Websocket Support for Subscriptions will be or could be added?

In my case, this is currently for interacting with Hasura subscriptions.
I could work on this and PR, since I've already done this on an extension of my own.
I'd rather merge it here so I can simply use the official extension and drop my extension.

Let me know, thanks!

**Comment by lukadriel7** [comment]
Hello, I haven't tried it personally but I think using the apolloClientBeforeCreate hook located in src/quasar-app-extension-apollo/apollo-client-hooks.js, you are able to change the link of the apolloClient at your convenience before it's creation. You could setup a link in a different js file following [this guide](https://apollo.vuejs.org/guide/apollo/subscriptions.html), and import it in the apollo-client-hooks to replace the default link. I created my own link using apollo-upload-client that way and it seems to work. Maybe try and let us know how it went.

**Comment by lukadriel7** [comment]
I currently do not have acces to a graphql server so i wrote it as I though but you can try the following:

Code for the link in separate file:
```
import { HttpLink } from "apollo-link-http";
import { split } from "apollo-link";
import { WebSocketLink } from "apollo-link-ws";
import { getMainDefinition } from "apollo-utilities";
import fetch from "node-fetch";
import { w3cwebsocket } from "websocket";

const onServer = process.env.SERVER;
const httpLinkConfig = {
  uri: "https://countries.trevorblades.com/"
};

const wsLinkConfig = {
  uri: "ws://localhost:3000/subscriptions",
  options: {
    reconnect: true
  }
};

if (onServer) {
  httpLinkConfig.fetch = fetch;
  wsLinkConfig.webSocketImpl = w3cwebsocket;
}
// Create the http link
const httpLink = new HttpLink(httpLinkConfig);

// Create the subscription websocket link
const wsLink = new WebSocketLink(wsLinkConfig);

const link = split(
  // split based on operation type
  ({ query }) => {
    const definition = getMainDefinition(query);
    return (
      definition.kind === "OperationDefinition" &&
      definition.operation === "subscription"
    );
  },
  wsLink,
  httpLink
);

export { link };

```

Code in the hook file: 
```
import { link } from "../js/apollo";

export function apolloClientBeforeCreate({ apolloClientConfigObj }) {
  apolloClientConfigObj.link = link;
  // if needed you can modify here the config object used for apollo client
  // instantiation
}

export function apolloClientAfterCreate(/* { apolloClient, app, router, store, ssrContext, urlPath, redirect } */) {
  // if needed you can modify here the created apollo client
}

```

P.S.: Do not forget to install all dependencies and change the urls to match your endpoint.
Also please let me know how it went

**Comment by ejez** [comment]
Thanks @lukadriel7 , the provided hooks allow full customization of the client.

**Comment by lukadriel7** [comment]
@ejez  Happy it worked out
