### ISSUE TITLE
Document how to add connect to Apollo Dev Tools

### ISSUE THREAD

**Issue by agritheory** [quasarframework/app-extension-apollo#38]
I _think_ you just drop `connectToDevTools: true` into `apollo-client-config.js` but that doesn't match the [Apollo DevTools](https://github.com/apollographql/apollo-client-devtools#configuration) documentation which says to put it into the `ApolloClient` constructor.

**Comment by smolinari** [comment]
The Apollo Dev Tools work in dev mode. I wouldn't turn it on in production. 

Scott

**Comment by agritheory** [comment]
Thanks Scott, what steps would I need to take to see them working?
This issue is a request for additional documentation not a bug report.

**Comment by smolinari** [comment]
To see dev tools working? You just install the extension in Chrome and it should show when Apollo is active, i.e. when you start up your Quasar app with this AE installed.

https://chrome.google.com/webstore/detail/apollo-client-developer-t/jdkknkkbebbapilgoeccciglkfbmbnfm

Scott
