### ISSUE TITLE
Unknown vue-apollo types in typescript

### ISSUE THREAD

**Issue by stphdenis** [quasarframework/app-extension-apollo#39]
We need to add `"vue-apollo"` in `tsconfig.json` when working with `typescript` :
```json
{
  "compilerOptions": {
    "types": ["quasar", "vue-apollo"]
  }
}
```

**Comment by IlCallo** [comment]
Being "vue-apollo" referenced into the boot file, TS should automatically pick up the typings regardless of the typescript configuration.
Can you elaborate a bit on your suggestion?

**Comment by stphdenis** [comment]
With new version of `Quasar`, now it works as you say.
