### ISSUE TITLE
Adding new ApolloClients to existing ApolloProvider from config file

### ISSUE THREAD

**Issue by danileks** [quasarframework/app-extension-apollo#40]
I want to create new apollo client and add it to existing apollo provider, but i can’t

What I try:

- modify apollo-client-config.js, adding to default section additionalConfig

- saw instruction for multiple clients https://apollo.vuejs.org/guide/multiple-clients.html

Without this new extension I can create ApolloProvider manually and add ApolloClients, but here I noticed, that apollo.js register only one 'defaultClient' ApolloClient.

`const apolloProvider = new VueApollo({ defaultClient: apolloClient })`

**Comment by Carleslc** [comment]
The same applies if we want other custom VueApollo options. For instance, I'd like to add
```
defaultOptions: {
  $query: {
    loadingKey: 'loading'
  }
}
```
to the apolloProvider.

How that can be achieved? Maybe an _apollo-provider-config.js_ could be created like the config file for the apollo client.

**Comment by ejez** [comment]
Thank you for the feedback! Will work on this soon.
