### ISSUE TITLE
SSR mode in production

### ISSUE THREAD

**Issue by DroidFone** [quasarframework/app-extension-apollo#46]
The method of building and deploying dist/ssr (copy, yarn install, yarn start) gives 500 error but works if quasar project root node_modules folder is present.

Also, .graphql files pointed in src are unavailable in dist folder.

**Comment by ejez** [comment]
Thanks for reporting, you can solve the issue by moving the ext from your app "dev dependencies" to the app "dependencies". 

The root issue is described here https://github.com/quasarframework/quasar/pull/6405

I appreciate if you add a comment there also (the more people complaining, the more it gets considered)
