### ISSUE TITLE
Type 'ExecutionResult' is not generic.

### ISSUE THREAD

**Issue by M1chaelTran** [quasarframework/app-extension-apollo#49]
Could we please update `apollo-link` to the latest version `1.2.14` to resolve this issue?
https://github.com/apollographql/apollo-link/issues/1261

As the latest version has the fix
https://github.com/graphql/graphql-js/pull/2490

My current workaround is to install the latest `apollo-link` myself.
However, I would imagine other running into this error and wasting time to figure it out.

**Comment by smolinari** [comment]
Um. The dependency on `apollo-link` has the "^" upgrade caret. So, if you run `quasar upgrade -i` (practically the same as running yarn upgrade) it should update any dependencies too. 

Scott
