### ISSUE TITLE
Subscription support "native"

### ISSUE THREAD

**Issue by strikeout** [quasarframework/app-extension-apollo#65]
Hi!

I was able to enable Apollo subscriptions with the help of the instructions in #37 but for the HTTP/WS link split the options in apollo-client-config are ignored and have to be recreated in the link definition. 
Can this be made native maybe, like if a WS config is found, also create the wsLink in create-apollo-client.js and utilize the config in quasar-extension.json and apollo-client-config.js?

**Comment by smolinari** [comment]
I'm not completely sure what you mean. But, I think I know what you mean, and if I am right, you should be able to wrap the ws link object creation code inside a function and pass the config info to it to use it, instead of just calling the object it creates.  

Scott

**Comment by smolinari** [comment]
Stale and question answered. Closing. 

Scott
