### ISSUE TITLE
How set request headers?

### ISSUE THREAD

**Issue by magersoft** [quasarframework/app-extension-apollo#67]
Hi! Please help me. How extend ApolloClient config and set custom request headers?

My current solution not working. In **apollo-client-hooks.js**
```javascript
export function apolloClientBeforeCreate({ apolloClientConfigObj }) {
  // if needed you can modify here the config object used for apollo client
  // instantiation

  const httpLink = createUploadLink({
    uri: API_URI
  });

  const wsLink = new WebSocketLink({
    options: {
      connectionParams: {
        Authorization: getToken()
      },
      reconnect: true
    },
    uri: WS_URI
  });

  const authMiddleware = new ApolloLink((operation, forward) => {
    operation.setContext({
      headers: {
        Authorization: getToken()
      }
    });
    return forward(operation);
  });

  const combinedLinks = split(
    ({ query }) => {
      const { kind, operation } = getMainDefinition(query);
      return kind === 'OperationDefinition' && operation === 'subscription';
    },
    wsLink,
    httpLink
  );

  const errorLink = onError(({ graphQLErrors, networkError }) => {
    if (graphQLErrors) {
      graphQLErrors.map(({ message }) => {
        console.error(`Unexpected error: ${message}`);
        return message;
      });
    }
    if (networkError) {
      console.error(`Network Error: ${networkError}`);
    }
  });

  apolloClientConfigObj = {
    ...apolloClientConfigObj,
    link: ApolloLink.from([errorLink, concat(authMiddleware, combinedLinks)])
  };

  apolloClientConfigObj.cache.writeData({
    data: {
      ...state
    }
  });
}

**Comment by magersoft** [comment]
Ooops! Just needed
```javascript
apolloClientConfigObj.link = ApolloLink.from([errorLink, concat(authMiddleware, combinedLinks)]);

**Comment by Pero122** [comment]
What is the "concat" method? I can't find it in the documentation

**Comment by smolinari** [comment]
@Pero122 - We have discussions open, so please ask questions there and just link to this discussion here please, if you need the reference (and in the future). Thanks.

To answer your questions, it's a function exported from Apollo Client. https://github.com/apollographql/apollo-client/blob/92fa8ffd18f4698b98b279613d4f2ddc8b294465/src/link/core/ApolloLink.ts#L84

`import { concat } from '@apollo/client'`

Scott

**Comment by Pero122** [comment]
I just want to say one more thing, regarding the original posted code for future reference.

The problem with the original code is this part.
```
  apolloClientConfigObj = {
    ...apolloClientConfigObj,
    link: ApolloLink.from([errorLink, concat(authMiddleware, combinedLinks)])
  };
```
That is the problem because objects are passed as reference, so instead of changing the original object (we want this so the modified object can be send when constructing apollo client) we are actually creating a new object and modifying the new object instead of the original config object (in this case this is bad, and we don't want this, because the object that will be send is not changing).

So just replace 
```
  apolloClientConfigObj = {
    ...apolloClientConfigObj,
    link: ApolloLink.from([errorLink, concat(authMiddleware, combinedLinks)])
  };
```
With
```apolloClientConfigObj.link = ApolloLink.from([errorLink, concat(authMiddleware, combinedLinks)])```
