### ISSUE TITLE
Duplicate data rendered on client side while using ssr

### ISSUE THREAD

**Issue by lukadriel7** [quasarframework/app-extension-apollo#68]
Hello, I recently started trying the extension with ssr and unless I am doing something horribly wrong, it seems that the data are rendered twice. Once prefetched by the server, and again instead of using data from the server, the client also fetch data and renders it after the server render. So we end up with duplicate data.
I started a new quasar project, added the extension and fetch data from [graphql countries](https://countries.trevorblades.com/)
using smart queries. No custom addition

quasar: "1.13.2"
quasar/app: "2.0.9",
quasar-app-extension-apollo: "1.0.0-beta.6"

**Comment by lukadriel7** [comment]
So I did some digging and found out that the apolloState wasn't rendered using the code injected in index.template.html by this extension. I don't know how it works but getting rid of the condition seems to work.

before:
```
<% // added by 'quasar-app-extension-apollo' %>
    <% if (ctx.mode.ssr && process.env.ssr) { %>
      {{{ renderState({ contextKey: 'apolloState', windowKey: '__APOLLO_STATE__' }) }}}
    <% } %>

```
after:
```
{{{ renderState({ contextKey: 'apolloState', windowKey: '__APOLLO_STATE__' }) }}}

```
If anyone knows why it doesn't work in the first occurrence please let me know.
Thanks in advance.

**Comment by lukadriel7** [comment]
It would seem that only using the `ctx.mode.ssr` works and the `process.env.ssr` breaks the code
What I ended up using:
```
<% if (ctx.mode.ssr) { %>
      {{{ renderState({ contextKey: 'apolloState', windowKey: '__APOLLO_STATE__' }) }}}
<% } %>
```

**Comment by smolinari** [comment]
Can you try this please?

```
 <% if (ctx.mode.ssr && process.env.MODE === 'ssr') { %>
```

Scott

**Comment by lukadriel7** [comment]
@smolinari Thank you, this works great. Will it be updated soon ?

**Comment by smolinari** [comment]
I'll see if I can get an update out this weekend. 

Scott

**Comment by lukadriel7** [comment]
fixed with merge of #72

**Comment by smolinari** [comment]
@lukadriel7 - thanks and sorry it's taken so long.

Scott

**Comment by lukadriel7** [comment]
@smolinari no worries, 2020 was just that crazy of a year 😂

**Comment by ipalestine** [comment]
how to implement this in quasar 2 that have index.html instead of index.template.html

**Comment by smolinari** [comment]
@ipalestine - Please to add to an old closed issue. Start a new issue and reference this issue in it if you need to. 

Scott
