### ISSUE TITLE
Option to choose extension boot order

### ISSUE THREAD

**Issue by lukadriel7** [quasarframework/app-extension-apollo#70]
Hello again, is it possible to add an option to choose the boot order ? At the moment the extension boot is added using push putting it after the boot files defined in quasar configuration. If there were an option to choose whether to unshift or push the boot file, it would help. Specifically when using a router-auth boot file to determine if the user is logged in at each route navigation.

**Comment by smolinari** [comment]
How are you logging in the user? I ask, because normally you'd need to contact the server first to validate credentials and for that, you need the GraphQL connection. 

Scott

**Comment by lukadriel7** [comment]
I am using laravel sanctum and I check the user log status based on the cookies. The user logs in from a standard login page. I created a boot file that check before each route navigation if the user is connected.

**Comment by smolinari** [comment]
And, how do you check if a user is "connected"? Somehow you need to connect (via GraphQL?) to the server, right? So, the first thing should be, send a request to the server about the user at hand (and validate access token/ session) and if all is well, the user can continue. If not, they get redirected to your login page. In other words, your SPA should access the API server first, then route the user accordingly. The boot sequence should be fine.  

Scott

**Comment by Arsync** [comment]
GraphQL might not be a part of authentication process, as there can exists dedicated identity server, STS. 
![image](https://user-images.githubusercontent.com/41461678/92318541-538e4180-f016-11ea-845d-384eae3f8078.png)
First, SPA communicates with other URI (token issuer) via oidc-client, then passed access token to the API.

So login page does not touch apollo, as there is no token yet. It shows transient screen, which launches browser redirect to STS with OpenID Connect / OAuth 2 process. When user is logged in at STS (like Google does), it redirects back to SPA (to the 'complete sign-in' page, specified in the STS configuration for that client).

In application workflow, there is action, known as 'silent refresh' where tokens are rotating in the background (within iframe with redirects to STS and back).

**Comment by Arsync** [comment]
Found that we can set `lazy: true` to prevent auto-connection before any client action being allowed.
SubscriptionClient parameters can be found at [this](https://www.npmjs.com/package/subscription-client?activeTab=readme#constructorurl-options-websocketimpl) description.

So original question is not about current 'apollo extension' repo, but how Quasar boot system works to exclude some steps from it.

**Comment by lukadriel7** [comment]
@smolinari Actually, you are right, I was using the connection in the wrong place of the boot file.
@Arsync I don't understand what you mean

**Comment by Arsync** [comment]
> I don't understand what you mean

This will manifest itself when you start using websockets and subscriptions. So I've looked for exactly same solution to disable boot files. But found just 'lazy' property:

```JS
// apollo-client-hooks
export function apolloClientBeforeCreate({ apolloClientConfigObj, app /*, router, store, ssrContext, urlPath, redirect */ })
{
    const subClient = new SubscriptionClient(
        process.env.API_GRAPHQL_WSS_URI,
        {
            lazy: true, // <-- this one to get connected on first API call
            reconnect: true,
            timeout: 30000,
            connectionParams: getConnectionParams(app.identity), // solution-specific function, nevermind
        }
    );

    const link = new WebSocketLink(subClient);
	
    apolloClientConfigObj.link = link;
}
```

**Comment by smolinari** [comment]
This question seems answered so closing. 

Scott
