### ISSUE TITLE
Setting auth headers

### ISSUE THREAD

**Issue by csterritt** [quasarframework/app-extension-apollo#73]
Hey -- thanks for doing this app extension, it's really great to have!

I'm using a back-end site which gives hasura+postgres as a service (NHost.io, highly recommended).  They have a very nice authentication system as well.

So my question is that I have to set the `Authorization: Bearer` header.  I can set it in the `apollo-client-config.js` file, and that works, but then I (apparently) have to force a refresh of the page when someone logs in or out, to force a rebuild of the Apollo client.

Is there a better way to change the headers sent, past configuration time?  I'd like to do it then anyway, because I feel like if the sign-in is slow, it may cause a race condition and the `apollo-client-config.js` code will run before I can get the bearer token, since the sign-in is async.

Thanks for any help!

**Comment by lukadriel7** [comment]
Hello @csterritt , I think one way to do it is using axios as the fetch method. 
You should install @lifeomic/axios-fetch, export the default axios from the boot file and create a new link using axios for your apollo config. I am using apollo-upload-client but you can replace it with apollo-link-http

axios boot file:
```
import Vue from "vue";
import Axios from "axios";
const axios = Axios.create();
Vue.prototype.$axios = axios;
export { axios };
```
apollo-client-hooks file:
```
import { axios } from "boot/axios";
import { buildAxiosFetch } from "@lifeomic/axios-fetch";
import { createHttpLink } from "apollo-link-http";

export function apolloClientBeforeCreate({ apolloClientConfigObj }) {
  apolloClientConfigObj.link = createUploadLink({
    uri: process.env.GRAPHQL_URI,
    fetch: buildAxiosFetch(axios)  
  });
}

export function apolloClientAfterCreate(/* { apolloClient, app, router, store, ssrContext, urlPath, redirect } */) {
  // if needed you can modify here the created apollo client
}
```

That way you can always handle the header with axios from anywhere in your program by for example following the tips in [this](https://stackoverflow.com/questions/43051291/attach-authorization-header-for-all-axios-requests) answer.
I hope it helps solve your problem.

**Comment by csterritt** [comment]
Thanks @lukadriel7!  I'll try that out soon and post back what I find.

**Comment by lukadriel7** [comment]
@csterritt no problem, there is also the option of using the [recommended way](https://www.apollographql.com/docs/react/v2.6/networking/authentication/#header) of `apollo client` if you only use graphql for queries. I use this method because I also make REST API calls and some customization for file upload. You will have to put the apollo code in `apollo-client-hooks.js`.

**Comment by csterritt** [comment]
Thanks @lukadriel7 -- I tried setting up the `apollo-client-hooks.js` but I may have done it wrong, as it appears to only be called once, not on each query, and the token may have changed since the last call.

I'm currently doing simple imperative code like:

~~~ js
const token = // retrieve the current token
const headers = {}
if (token != null) {
    headers.Authorization = `Bearer ${token}`
}

await apollo.query({
    query,
    variables,
    context: { headers },
})
~~~

Which works for `query` and `mutate`.  This works fine, but it'd be nice to able to do the declarative thing as well.

**Comment by touha98** [comment]
@csterritt you can set token from within a vue file like this when a new user login is successful:
```
 localStorage.setItem("AUTH_TOKEN", token);
 this.$axios.defaults.headers.common["authorization"] ="Bearer " + token;
```

**Comment by touha98** [comment]
@csterritt using the axios fetch method @lukadriel7 mentioned above,
 you can set token from within a vue file like this when a new user login is successful:
```
 localStorage.setItem("AUTH_TOKEN", token);
 this.$axios.defaults.headers.common["authorization"] ="Bearer " + token;
```

and in `boot/axios.js` file:
```
import Vue from "vue";
import Axios from "axios";
const axios = Axios.create();
const token = localStorage.getItem("AUTH_TOKEN");
if (token) {
  axios.defaults.headers.common["authorization"] = "Bearer " + token;
}
Vue.prototype.$axios = axios;
export { axios };
```

**Comment by smolinari** [comment]
There is no reason to use axios with apollo-client to set headers. You can set the headers per request as noted by @lukadriel7 's link. The `setContext` method is ran for each request. So, you set your token in storage during login, that sets the outbound header on the next call. 

Scott

**Comment by lukadriel7** [comment]
@csterritt this should be the way to do it : 

apollo-client-hooks.js
```
import { ApolloClient } from 'apollo-client';
import { createHttpLink } from 'apollo-link-http';
import { setContext } from 'apollo-link-context';
import { InMemoryCache } from 'apollo-cache-inmemory';

export function apolloClientBeforeCreate({ apolloClientConfigObj }) {
  const httpLink = createHttpLink({
  uri: YOUR_GRAPHQL_ENDPOINT,
});

const authLink = setContext((_, { headers }) => {
  // get the authentication token from local storage if it exists
  const token = localStorage.getItem('token');
  // return the headers to the context so httpLink can read them
  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : "",
    }
  }
});
  apolloClientConfigObj.link = authLink.concat(httpLink);
}

export function apolloClientAfterCreate(/* { apolloClient, app, router, store, ssrContext, urlPath, redirect } */) {
  // if needed you can modify here the created apollo client
}

```

**Comment by csterritt** [comment]
Thanks @touha98, @smolinari, and @lukadriel7!  I appreciate all the help!

**Comment by csterritt** [comment]
@lukadriel7 That solution works perfectly -- thanks!

For future reference, the following two `import`s aren't needed:

    import { ApolloClient } from 'apollo-client'
    import { InMemoryCache } from 'apollo-cache-inmemory'

**Comment by smolinari** [comment]
Closing as question is answered.

Scott
