### ISSUE TITLE
Compatibility issues with @quasar/dotenv

### ISSUE THREAD

**Issue by lukadriel7** [quasarframework/app-extension-apollo#74]
Hello, I didn't know where to report so I guess I will do it on both repository.
@quasar/apollo extension has trouble using @quasar/dotenv variables when in quasar.extensions.json,
dotenv is configured before apollo. It adds some quotation marks around the variable causing issues on the GRAPHQL_URI.

changing the order fixes the problem but still very ennoying issue and difficult to debug.

**Comment by smolinari** [comment]
Closing as stale. Thanks for the note. 

Scott
