### ISSUE TITLE
Asynchronous Calls in Apollo Configuration Hooks

### ISSUE THREAD

**Issue by wyepez** [quasarframework/app-extension-apollo#81]
Hello,

I have a front-end application that should be deployed on-premises in different customers, hence it needs different API URLs for every customer. Also, this front-end application is deployed using a docker image. So far, every time that I want to update a customer, I have to build the front-end application with this command adjusted to every customer: **GRAPHQL_URI=https://prod.customer1.com/graphql quasar build**. So I end up having a docker image per customer. What I really want is just to have one single docker image and in the moment of instantiating a container, somehow set the graphql URI for that customer.

The only idea that I have is to put a config.json file in the public folder of the quasar app and from there fetch it and extract the URI per customer. In this way, every time that I instantiate a docker container, I set the config.json file with the URI for that customer.

The problem that I'm facing is that in order to consume that config.json, the API call is asynchronous and it's not working in this way.

**public/config.json**

```
{
    "GRAPHQL_URI": "https://prod.example.com/graphql/v2"
}
```

**src/apollo/apollo-client-config.js**

```
export default async function (/* { app, router, store, ssrContext, urlPath, redirect } */) {
  let GRAPHQL_URI
  if (process.env.DEV) {
    const config = await fetch('config.json').then(response => response.json())
    GRAPHQL_URI = config.GRAPHQL_URI
  }

  return {
    default: {
      // 'apollo-link-http' config
      // https://www.apollographql.com/docs/link/links/http/#options
      httpLinkConfig: {
        // you can define the 'uri' here or using an env variable when
        // running quasar commands, for example:
        // `GRAPHQL_URI=https://prod.example.com/graphql quasar build`
        // `GRAPHQL_URI=https://dev.example.com/graphql quasar dev`
        uri: process.env.GRAPHQL_URI || GRAPHQL_URI || 'http://localhost:5000/api'
      },

      // 'apollo-cache-inmemory' config
      // https://www.apollographql.com/docs/react/caching/cache-configuration/#configuring-the-cache
      cacheConfig: {},

      // additional config for apollo client
      // https://github.com/apollographql/apollo-client/blob/version-2.6/docs/source/api/apollo-client.mdx#optional-fields
      additionalConfig: {}
    },

    // you can add more options or override the default config for a specific
    // quasar mode or for dev and prod modes. Examples:

    // ssr: {},

    // dev: {
    //   httpLinkConfig: {
    //     uri: process.env.GRAPHQL_URI || 'http://dev.example.com/graphql'
    //   }
    // },

    // prod: {
    //   httpLinkConfig: {
    //     uri: process.env.GRAPHQL_URI || 'http://prod.example.com/graphql'
    //   }
    // },

    // the following gets merged to the config only when using ssr and on server
    ssrOnServer: {
      additionalConfig: {
        // https://apollo.vuejs.org/guide/ssr.html#create-apollo-client
        ssrMode: true
      }
    },

    // the following gets merged to the config only when using ssr and on client
    ssrOnClient: {
      additionalConfig: {
        // https://apollo.vuejs.org/guide/ssr.html#create-apollo-client
        ssrForceFetchDelay: 100
      }
    }
  }
}
```

**Comment by smolinari** [comment]
I'm not a docker expert, so I'll pose a counter question. Instead of thinking of docker containers as per tenant app delivery units, could you think of them at a higher level as a builder and app server units (or services)? You'd only need two containers with the tenant apps being on a volume. One container would be singularly responsible for building the apps. The other singularly responsible for delivering/ serving the built apps. You'd probably need one more container for getting the apps onto the system (i.e. a file reception/ repo cloning service). With that model, I think you can build apps as you like (i.e. with the necessary endpoint entry) and just serve them as needed and can scale too (which is the goal of docker). Also, you could double this up and then have a  blue/ green deployment system too. Maybe? 

In general, I believe the resources of a docker container just for the delivery and/ or building of one SPA is overkill. That's just my point of view though. :)

Scott

**Comment by wyepez** [comment]
> I'm not a docker expert, so I'll pose a counter question. Instead of thinking of docker containers as per tenant app delivery units, could you think of them at a higher level as a builder and app server units (or services)? You'd only need two containers with the tenant apps being on a volume. One container would be singularly responsible for building the apps. The other singularly responsible for delivering/ serving the built apps. You'd probably need one more container for getting the apps onto the system (i.e. a file reception/ repo cloning service). With that model, I think you can build apps as you like (i.e. with the necessary endpoint entry) and just serve them as needed and can scale too (which is the goal of docker). Also, you could double this up and then have a blue/ green deployment system too. Maybe?
> 
> In general, I believe the resources of a docker container just for the delivery and/ or building of one SPA is overkill. That's just my point of view though. :)
> 
> Scott

What I understand is that in the end, I should build as many apps as customers. This is exactly what I don't want. The solution, as a whole, is not only the front-end, there is a back-end API, an authentication API, and multiple daemon services. And for every component of the solution, I have only one docker image. Later, when I run a docker container based on these images, I configure it per customer through environment variables (for example, the connection string of the database). Environment variables are something that is not suitable for SPAs because are executed on the client.

In other solution that I have, I don't use Graphql, I use REST and I have one docker image for the front-end application and I use the approach shown in my original post to get the initial URL for the back-end API. The problem is that I don't find a way to do the same thing for apollo+quasar

**Comment by smolinari** [comment]
Ok. So the front-end app itself is going to be generic, i.e. every tenant will use the same app, but just needs to hit different endpoints. Am I now understanding correctly? How about the backend APIs, are they, from a functional perspective, the same or are they tenant specific? I'd assume tenant specific, from what you've described. Just let me know if I'm wrong. 

Scott

**Comment by wyepez** [comment]
> Ok. So the front-end app itself is going to be generic, i.e. every tenant will use the same app, but just needs to hit different endpoints. Am I now understanding correctly? How about the backend APIs, are they, from a functional perspective, the same or are they tenant specific? I'd assume tenant specific, from what you've described. Just let me know if I'm wrong.
> 
> Scott

Yes, you are correct.
What I do for the rest of the components, i.e. for the back-end API, I set an environmental variable specifying the connection string for the database at the moment that I instantiate the docker container. The docker image remains generic, like a template for all other installations. But the front-end app cannot use environmental variables in the docker container because the SPA doesn't run in the container, it runs on the user's computer.

In another solution, that uses Vue as a front-end app and consumes a REST API with axios, there is a file called config.json located in the public folder of the app. When the SPA is initiating, I consume this config.json file that holds the URL for the back-end API. This config.json file is modified with the correct back-end API's URL after the docker container is created because this URL is tenant-specific.

When I try to do the same thing with the apollo extension, as it's shown in my original post (apollo-client-config.js), the URL is not set correctly and I think it's because of the asynchronous call. Actually, the URL ends up being a generic /graphql URL, it's not even the default harcoded one.

This is what I try to do. In the end, also I post the reason behind this because maybe someone has a better idea.

**Comment by wyepez** [comment]
Can anyone help me? Any ideas? Or there is no way to set the API URL after building the Vue app?

**Comment by ejez** [comment]
> This config.json file is modified with the correct back-end API's URL after the docker container is created because this URL is tenant-specific.

You might use this same method, you can modify the built spa when creating the container, change the uri using a shell command (sed for example). The new uri can be provided to the container using an env variable.

**Comment by ejez** [comment]
You can also do the following:

`public/config.js`

```js
var myAppConfig = {
  graphql_uri: 'https://mydearcustomer.example.com/graphql',
}
```

`src/index.template.html`

```html
...
<body>
  <script type="text/javascript" src="/config.js"></script>
  <!-- DO NOT touch the following DIV -->
  <div id="q-app"></div>
  ...
</body>
```

`src/apollo/apollo-client-hooks.js`

```js
import { HttpLink } from 'apollo-link-http'

export function apolloClientBeforeCreate(
  {
    apolloClientConfigObj,
  } /* { apolloClientConfigObj, app, router, store, ssrContext, urlPath, redirect } */
) {
  // if needed you can modify here the config object used for apollo client
  // instantiation
  apolloClientConfigObj.link = new HttpLink({
    uri: window.myAppConfig.graphql_uri,
  })
}

export function apolloClientAfterCreate(/* { apolloClient, app, router, store, ssrContext, urlPath, redirect } */) {
  // if needed you can modify here the created apollo client
}
```

`Dockerfile`

```
FROM nginx:1.19.6-alpine
COPY ./dist/spa /usr/share/nginx/html
```

```sh
docker build -t mynamespace/myapp .
```

Now you can mount a per customer config in the docker containers:

```sh
docker run -v /absolute/path/to/customer1-config.js:/usr/share/nginx/html/config.js -p 8080:80 mynamespace/myapp
```

**Comment by ejez** [comment]
Note: The issue title is not precisely reflecting what you want to achieve.

**Comment by ejez** [comment]
> The only idea that I have is to put a config.json file in the public folder of the quasar app and from there fetch it and extract the URI per customer. In this way, every time that I instantiate a docker container, I set the config.json file with the URI for that customer.
> 
> The problem that I'm facing is that in order to consume that config.json, the API call is asynchronous and it's not working in this way.

I do not see any reason why the extension functions should not be async, I will submit a PR to make all the extension functions async. Thanks for bringing this up.

When that PR is merged you'll be able to do:
`public/config.js`
```js
export default {
  graphql_uri: 'https://generic-customer.example.com/graphql'
}
```

`apollo-client-config.js`
```js
export default async function (/* { app, router, store, ssrContext, urlPath, redirect } */) {
  const { default: myAppConfig } = await import(
    /* webpackIgnore: true */ '/config.js'
  )

  return {
    default: {
      httpLinkConfig: {
        uri:
          process.env.GRAPHQL_URI || myAppConfig.graphql_uri || 'https://example.com/graphql'
      },
...
```
```sh
docker build -t mynamespace/myapp .
docker run -v /absolute/path/to/customer1-config.js:/usr/share/nginx/html/config.js -p 8080:80 mynamespace/myapp
```

**Comment by ejez** [comment]
PR https://github.com/quasarframework/app-extension-apollo/pull/82

**Comment by wyepez** [comment]
Sorry for the late response. Thank you @ejez for your help. I tested your alternatives and they work like a charm. Also, thank you for your PR.

**Comment by ejez** [comment]
@wyepez new version available with async functions.
https://www.npmjs.com/package/@quasar/quasar-app-extension-apollo

**Comment by smolinari** [comment]
Closing. The current version is async.

Scott
