### ISSUE TITLE
Setting the tokenName option on apolloClientConfigObj is not having any effect?

### ISSUE THREAD

**Issue by x-ji** [quasarframework/app-extension-apollo#92]
When instantiating `apolloClient` there is an option called `tokenName`, as seen at e.g. [this page](https://apollo.vuejs.org/guide/multiple-clients.html). Previously I've used the option in another project which uses `vue-apollo` directly, and it seems to work exactly as advertized, i.e. it will always set the `authorization` header of every request with the token stored under a key named `tokenName` from LocalStorage. However, when I try to set it in `apollo-client-hooks.js` with e.g. 

```js
export async function apolloClientBeforeCreate({ apolloClientConfigObj }) {
  apolloClientConfigObj.tokenName = "name";
}
```

no authorization header seems to be added to the request sent via apollo. In the end I managed to make it work by manually modifying the link and adding the authorization header to it. I wonder what the issue could be. I'm not sure if I'm missing something obvious here or if I misunderstood the option.

**Comment by smolinari** [comment]
Yeah. I'm not sure where that `tokenName` property is coming from or how it is handled. I'd suggest, as you have, to ignore it and just do the setting of the header via the normal header property. 

https://www.apollographql.com/docs/react/v2/networking/authentication/#header

Scott

**Comment by x-ji** [comment]
Sure. I think it's mentioned in vue-apollo's documentation https://vue-cli-plugin-apollo.netlify.app/guide/configuration.html#createapolloclient-options, but not in the original apollo documentation, thus it's quite confusing. I'll use the manual approach and will report again if I face further difficulties.
