### ISSUE TITLE
inline fragments IntrospectionFragmentMatcher error and in memory cache configuration not applied

### ISSUE THREAD

**Issue by maxiride** [quasarframework/app-extension-apollo#93]
A query using inline fragments gives the 

> You are using the simple (heuristic) fragment matcher, but your queries contain union or interface types. Apollo Client will not be able to accurately map fragments. To make this error go away, use the `IntrospectionFragmentMatcher` as described in the docs: https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher

According to the documentation on [Using fragments with unions and interfaces](https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces) this issue should be approached [by informing the client of possible types to expect from a query](https://www.apollographql.com/docs/react/data/fragments/#defining-possibletypes-manually). However, after doing so the above error persist and the client is unable to perform queries which feature inline fragments.

Example query within the ApolloQuery component:
```vue
  <ApolloQuery
    :query="gql => gql`${this.query}`"
    :variables="{ ep: this.$route.params.id }"
  >
    <template v-slot="{ result: { loading, error, data } }">
      <!-- Loading -->
      <div v-if="loading" class="loading apollo">Loading...</div>

      <!-- Error -->
      <div v-else-if="error" class="error apollo">An error occurred</div>

      <!-- Result -->
       <div v-else-if="data">{{ data }}</div>

      <!-- No result -->
      <div v-else class="no-result apollo">No result :(</div>
    </template>
  </ApolloQuery>
```

Example query with inline fragment (used with `this.query` above)
```gql
query HeroForEpisode($ep: Episode!) {
  hero(episode: $ep) {
    name
    ... on Droid {
      primaryFunction
    }
  }
}
```

`apollo.client.config.js` where the in memory cache configuration for possibleTypes should be applied:
```js
// 'apollo-cache-inmemory' config
// https://www.apollographql.com/docs/react/caching/cache-configuration/#configuring-the-cache
cacheConfig: {
  possibleTypes: {
    Character: ["Droid"],
  },
},
```

**Comment by maxiride** [comment]
A very verbose **workaround** is to specify the `no-cache` policy and query all the parent fields for every interface.

```gql
query HeroForEpisode($ep: Episode!) {
  hero(episode: $ep) {
    name
    ... on Droid {
      name
      primaryFunction
    }
  }
}
```

**Comment by smolinari** [comment]
What version of Apollo Client are you using?

Scott

**Comment by maxiride** [comment]
I'm sorry you are right, I must have made confusion after hitting dead ends for a couple hours.

I've installed the @quasar/apollo extension which is currently at the version: "@quasar/quasar-app-extension-apollo": "^1.0.0-beta.8", so I suppose I have whatever version gets shipped with it which is not listed in `package.json`.

Inspecting `yarn.lock` showed me that I have `apollo-client "^2.6.8"`

yarn.lock
```
"@quasar/quasar-app-extension-apollo@^1.0.0-beta.8":
  version "1.0.0-beta.8"
  resolved "https://registry.yarnpkg.com/@quasar/quasar-app-extension-apollo/-/quasar-app-extension-apollo-1.0.0-beta.8.tgz#6cd17eecc99f61c7a4f4e2c28c8473208270bf4d"
  integrity sha512-1yEWA/1v/GX/DLiylK74HL461DmWUOQwycu3htIQW81k61FOt1NV118O1WeuR6X+j53Ss9cPFpekCjkubFirmQ==
  dependencies:
    apollo-cache-inmemory "^1.6.5"
    apollo-client "^2.6.8"
    apollo-link "^1.2.13"
    apollo-link-http "^1.5.16"
    graphql "^14.6.0"
    graphql-tag "^2.10.3"
    node-fetch "^2.6.0"
    vue-apollo "^3.0.3"
    webpack-merge "^4.2.2"
```

First thing first I suppose I should update to apollo-client v3 (if the quasar apollo extension supports it) but [I still see](https://www.npmjs.com/package/@quasar/quasar-app-extension-apollo) that 1.0.0-beta.8 is the latest version so I am unsure on how to proceed. 

I would definitively prefer to use `possibleTypes` since its way easier and straightforward to implement.

**Comment by smolinari** [comment]
Unfortunately, we are in the middle of updating the AE to use vue-apollo 4, which supports Apollo 3 out of the box. The only thing is, it will also only support Quasar v2 (Vue3). 

You can try to upgrade to Apollo 3 and see what happens. I'm just not sure all the APIs are the same and thus Vue-Apollo won't work with it. 

Scott

**Comment by smolinari** [comment]
@ejez - Do you have any tips by chance on getting v1 of the Apollo AE to version 3 of Apollo Client?

Scott

**Comment by ejez** [comment]
https://v4.apollo.vuejs.org/guide/

> This library integrates apollo in your Vue components with declarative queries. Compatible with **Vue 2.0+** and 3.0+.

As mentioned, vue apollo v4 should work with vue v2 (and quasar v1)

Do not use the app extension v1, as it relies on the older API. Instead, do the following:

1. Let's start clean, remove older versions:

```sh
quasar ext remove @quasar/apollo
```

Its dependencies should be removed. Remove any apollo related package installed manually.

2. Install vue-apollo and its deps:

```sh
yarn add graphql graphql-tag @apollo/client @vue/apollo-composable react
yarn add --dev @types/react
# Note: if react is not installed you might get a dependency error from apollo client.
```

3. Create a file for configuring apollo `src/apollo/options.ts`:
<details>
  <summary>Click to expand!</summary>

```typescript
import {
  ApolloClientOptions,
  createHttpLink,
  InMemoryCache,
} from "@apollo/client";

export function getClientOptions() {
  return <ApolloClientOptions<unknown>>Object.assign(
    // General options.
    <ApolloClientOptions<unknown>>{
      link: createHttpLink({
        uri: process.env.GRAPHQL_URI || "https://example.com/graphql",
      }),

      cache: new InMemoryCache({}),
    },

    // Specific Quasar mode options.
    process.env.MODE === "spa"
      ? {
          //
        }
      : {},
    process.env.MODE === "ssr"
      ? {
          //
        }
      : {},
    process.env.MODE === "pwa"
      ? {
          //
        }
      : {},
    process.env.MODE === "bex"
      ? {
          //
        }
      : {},
    process.env.MODE === "cordova"
      ? {
          //
        }
      : {},
    process.env.MODE === "capacitor"
      ? {
          //
        }
      : {},
    process.env.MODE === "electron"
      ? {
          //
        }
      : {},

    // dev/prod options.
    process.env.DEV
      ? {
          //
        }
      : {},
    process.env.PROD
      ? {
          //
        }
      : {},

    // For ssr mode, when on server.
    process.env.MODE === "ssr" && process.env.SERVER
      ? {
          ssrMode: true,
        }
      : {},
    // For ssr mode, when on client.
    process.env.MODE === "ssr" && process.env.CLIENT
      ? {
          ssrForceFetchDelay: 100,
        }
      : {}
  );
}
```

</details>

(adapt it if you don't use typescript)

4. Create a boot file `src/boot/apollo.ts`
<details>
  <summary>Click to expand!</summary>

```typescript
import { ApolloClient } from "@apollo/client";
import { boot } from "quasar/wrappers";
import { getClientOptions } from "src/apollo/options";

let apolloClient: ApolloClient<unknown>;

export default boot(() => {
  const options = getClientOptions();
  apolloClient = new ApolloClient(options);
});

export { apolloClient };
```

</details>

Enable it in `quasar.conf.js`

5. Provide the created client to the rest of your components using `App.vue`:
<details>
  <summary>Click to expand!</summary>

```typescript
import { DefaultApolloClient } from '@vue/apollo-composable'
import { defineComponent, provide } from '@vue/composition-api'
import { apolloClient } from 'src/boot/apollo'

 export default defineComponent({
 ...
  setup () {
    provide(DefaultApolloClient, apolloClient)
  }
 })
```

</details>

For usage instructions, take a look at https://v4.apollo.vuejs.org/guide-composable/query.html

**Comment by ejez** [comment]
After the above setup is done, you can now do something like:

`src/apollo/options.ts`
```typescript
...
      cache: new InMemoryCache({
        possibleTypes: {
          ...
        }
      })
...
```

**Comment by maxiride** [comment]
Thank you very much @smolinari and @ejez  for all the clarifications and guidance to implement the new apollo client. Keep up the good work on the apollo extension!

**Comment by smolinari** [comment]
Awesome! Thanks @ejez !!! 👍 😀 

Scott
