### ISSUE TITLE
Accesssing apolloClient inside boot file?

### ISSUE THREAD

**Issue by Quasarman** [quasarframework/app-extension-apollo#94]
Hello,

is it possible to access the apolloClient inside a boot file.  I tried accessing it via app.apolloProvider inside one of my boot files but at the time the boot file gets loaded the app.apolloProvider prop does not seem to be initialized. Is it possible to change the boot order of the plugin so I can access it?

**Comment by ejez** [comment]
Hi @Quasarman

If you want to manipulate the apollo `client` or `provider` (after their creation) or their configs (before their creation), you can do so using the provided hooks. If that is not enough, you can unregister the extension by removing it from `quasar.extensions.json` and registering its boot file manually in `quasar.conf.js` in the order you need it in.

`quasar.extensions.json` 
```diff
{
...
-  "@quasar/apollo": {
-    "graphql_uri": "https://example.com/graphql"
-  }
...
}
```
`quasar.conf.js`
```diff
-module.exports = function (/* ctx */) {
+module.exports = function (ctx) {
...
     boot: [
+      '~@quasar/quasar-app-extension-apollo/src/boot/' + (ctx.mode.ssr ? 'apollo-ssr' : 'apollo'),
       'my-other-boot-file-that-should-run-after-apollo'
     ],
...
     build: {
      env: {
          ...
+        GRAPHQL_URI: process.env.GRAPHQL_URI // to allow overriding the uri with `GRAPHQL_URI=https://example.com/graphql quasar dev`
      },
```
(Take a look at https://github.com/quasarframework/app-extension-apollo/blob/182654829e90ef4e2d8ab43f3c96c3edb0d7adf6/src/index.js lines 8 and 15)

To explain why the extension boot file is run last, we used `conf.boot.push` which pushes the boot file to the end of the boot files array (may be not the best way).

**Comment by Quasarman** [comment]
Hello @ejez

Thanks for the detailed explantation this helps alot!
